// One-shot icon generator for PWA + apple-touch-icon.
// Run with: node scripts/build-icons.mjs
// Requires `sharp` (install transiently: `npm i -D --no-save sharp`).

import { readFileSync, writeFileSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'
import sharp from 'sharp'

const __dirname = dirname(fileURLToPath(import.meta.url))
const ROOT = join(__dirname, '..')
const PUBLIC = join(ROOT, 'public')

const SRC_SVG = readFileSync(join(PUBLIC, 'favicon.svg'), 'utf8')

// Pad the favicon onto a solid background for the safe-zone-aware "maskable"
// icon variants and the apple-touch-icon (iOS expects full-bleed PNG).
function paddedSvg({ size, padding, bg }) {
  const inner = size - padding * 2
  const innerB64 = Buffer.from(SRC_SVG).toString('base64')
  return `<svg xmlns="http://www.w3.org/2000/svg" width="${size}" height="${size}" viewBox="0 0 ${size} ${size}">
  <rect width="${size}" height="${size}" fill="${bg}"/>
  <image href="data:image/svg+xml;base64,${innerB64}" x="${padding}" y="${padding}" width="${inner}" height="${inner}"/>
</svg>`
}

async function render(svg, outPath, size) {
  await sharp(Buffer.from(svg))
    .resize(size, size)
    .png({ compressionLevel: 9 })
    .toFile(outPath)
  console.log(`✔ ${outPath}`)
}

// Maskable safe zone is the inner ~80% (per the spec). Pad ~12% on each side
// so the logo lives inside the mask radius on any platform.
const tasks = [
  { name: 'icon-192.png',         size: 192, pad: 24, bg: '#ffffff' },
  { name: 'icon-512.png',         size: 512, pad: 64, bg: '#ffffff' },
  { name: 'icon-maskable-512.png',size: 512, pad: 96, bg: '#F2EAD0' },
  { name: 'apple-touch-icon.png', size: 180, pad: 24, bg: '#ffffff' },
]

for (const t of tasks) {
  const svg = paddedSvg({ size: t.size, padding: t.pad, bg: t.bg })
  await render(svg, join(PUBLIC, t.name), t.size)
}

// Drop a tiny readme so the artifacts aren't mysterious.
writeFileSync(
  join(PUBLIC, 'icons.README.md'),
  '# App icons\n\nGenerated by `node scripts/build-icons.mjs` from `favicon.svg`. Rerun whenever the favicon changes.\n'
)
console.log('Done.')
